### ISSUE TITLE
How would you install without docker? but rather with HomeAssistantOS

### ISSUE THREAD

**Issue by RedGreenBaron** [skullydazed/meross_mqtt_ha#2]
Forgive me as I'm a newbie but I installed home assistant OS on my raspberry pi because it seemed like the simplest way
and seems to be working quite well for the little bits I have installed right now. managed to get Tasmota running without issue and now I would like to set up my meross plugs and my single switch to run offline but your instructions are for docker what would I have to do differently and how would I go about it?

thanks

**Comment by skullydazed** [comment]
This project isn't really in a good state to be used in general. You should take a look at https://github.com/albertogeniola/meross-homeassistant/issues/144.
